name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: autotools
      run: autoreconf -i
      
    - name: configure
      run: ./configure
      
    - name: Run Parasoft C/C++test
      # You may pin to the exact commit or the version.
      # uses: parasoft/run-cpptest-action@aeb0150eeb0f96098ad3bac53609fd462f88c4f6
      uses: parasoft/run-cpptest-action@1.0.1

    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
