name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: autotools
      run: autoreconf -i
      
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'cpp'
      
    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
